/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mayatm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 2003l
 */
public class NopTien extends javax.swing.JFrame {

    private String so = "";
    int update = 0;

    /**
     * Creates new form NopTien
     */
    public NopTien(String so) {
        initComponents();
        this.so = so;
    }

    public void ketnoi_2() {
        update = Integer.parseInt(txtNhapSoTienNop.getText());
        try {
            //Step1: load the driver class  
            //Step1: load the driver class  
            Class.forName("oracle.jdbc.driver.OracleDriver");
            //Step2: create  the connection object

            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:ORCL", "c##SA", "SA");
            //Step3: create the statement object
            con.setAutoCommit(false);

            String updateString_TK = "UPDATE TTTK SET SODUTK = (SODUTK + " + Integer.parseInt(txtNhapSoTienNop.getText()) + ") WHERE SOTK like '" + this.so + "' ";
            PreparedStatement updateTK = con.prepareStatement(updateString_TK);
            
            
            if (updateTK.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Nạp thành công " + update +" VND");
            } else {
                
            }
            
            String selectString = "SELECT SODUTK FROM TTTK WHERE SOTK LIKE '" + so + "'";
            PreparedStatement selectTTTK = con.prepareStatement(selectString, ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            //Step4: execute query
            ResultSet rs = selectTTTK.executeQuery();
            while (rs.next()) {
                update = rs.getInt(1);
            }
            JOptionPane.showMessageDialog(null, "Số tiền trong tài khoảng của bạn là được cập nhật là " + update +" VND");

            
            con.commit();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNhapSoTienNop = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnHuyGiaoDich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nhập số tiền cần nạp:");

        txtNhapSoTienNop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnXacNhan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuyGiaoDich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnHuyGiaoDich.setText("Hủy giao dịch");
        btnHuyGiaoDich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyGiaoDichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhapSoTienNop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnXacNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuyGiaoDich)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNhapSoTienNop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnHuyGiaoDich))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        ketnoi_2();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyGiaoDichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyGiaoDichActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnHuyGiaoDichActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyGiaoDich;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNhapSoTienNop;
    // End of variables declaration//GEN-END:variables
}
